on:
  push:
    branches: [ main, S003 ]
  pull_request:
    branches: [ main, S003 ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
@@ -27,3 +27,7 @@ jobs:
    - name: Install dependencies
      run:
        npm install

    - name: Run linter
      run:
        npm run lint

