name: Lint
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v3
        with:
          cmd: install 
      - uses: actions/checkout@v3
        with:
          cmd: eslint:github-action